"""Trial access codes: one per person, with an expiry and a revoke switch.

The deployment is advertised on LinkedIn, so codes go out to people who
arrive one at a time. A single shared code cannot be withdrawn from one
person without withdrawing it from everyone, and it says nothing about who
has been using it. Each code here carries a label (who it was for), an
optional expiry, and a use count.

Codes are stored as SHA-256 hashes, never in the clear, so a copy of the
database does not hand over working codes. A fast hash is right here where
it would be wrong for passwords: these codes are twelve random URL-safe
characters generated by `secrets`, about 70 bits, so there is no dictionary
to run and no human-chosen pattern to exploit. Lookup is by hash, which a
deliberately slow hash would make impossible anyway.

The short id printed beside each code is unrelated to the code itself, so
the listing can be read, kept and pasted around without leaking anything
usable.

This table lives in the same SQLite file as the response cache and the
usage counters, so the whole of the deployment's mutable state is the one
file to copy when backing up.
"""

from __future__ import annotations

import hashlib
import secrets
import sqlite3
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from .quota import LOCAL_TZ

_SCHEMA = """
CREATE TABLE IF NOT EXISTS access_code (
    code_hash    TEXT PRIMARY KEY,
    id           TEXT NOT NULL UNIQUE,
    label        TEXT NOT NULL,
    created_at   REAL NOT NULL,
    expires_at   REAL,
    revoked_at   REAL,
    uses         INTEGER NOT NULL DEFAULT 0,
    last_used_at REAL
);
"""

# Twelve URL-safe characters: short enough to read down a phone line,
# long enough that the ten-guesses-an-hour limit is not the only thing
# standing in the way.
CODE_BYTES = 9


def _hash(code: str) -> str:
    return hashlib.sha256(code.strip().encode("utf-8")).hexdigest()


def _when(value: Optional[float]) -> str:
    if value is None:
        return "—"
    return datetime.fromtimestamp(value, LOCAL_TZ).strftime("%Y-%m-%d %H:%M")


@dataclass(frozen=True)
class CodeRecord:
    id: str
    label: str
    created_at: float
    expires_at: Optional[float]
    revoked_at: Optional[float]
    uses: int
    last_used_at: Optional[float]

    def status(self, now: Optional[float] = None) -> str:
        now = time.time() if now is None else now
        if self.revoked_at is not None:
            return "revoked"
        if self.expires_at is not None and now >= self.expires_at:
            return "expired"
        return "active"


class AccessCodes:
    def __init__(self, db_path: Path):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as conn:
            conn.executescript(_SCHEMA)

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.row_factory = sqlite3.Row
        return conn

    def issue(self, label: str, days: Optional[int] = None,
              now: Optional[float] = None) -> tuple[str, CodeRecord]:
        """Mint a code. Returned once, in the clear; only its hash is kept."""
        now = time.time() if now is None else now
        code = secrets.token_urlsafe(CODE_BYTES)
        short_id = secrets.token_hex(3)
        expires_at = now + days * 86400 if days else None
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO access_code (code_hash, id, label, created_at, expires_at)"
                " VALUES (?, ?, ?, ?, ?)",
                (_hash(code), short_id, label.strip() or "unlabelled", now, expires_at),
            )
        return code, CodeRecord(short_id, label, now, expires_at, None, 0, None)

    def check(self, code: str, now: Optional[float] = None) -> Optional[CodeRecord]:
        """The record behind a code, if it is usable; otherwise None.

        A successful check counts a use. Revoked and expired codes are
        rejected here rather than deleted, so the listing keeps saying what
        was handed out and what became of it.
        """
        if not code.strip():
            return None
        now = time.time() if now is None else now
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM access_code WHERE code_hash = ?", (_hash(code),)
            ).fetchone()
            if row is None:
                return None
            record = _record(row)
            if record.status(now) != "active":
                return None
            conn.execute(
                "UPDATE access_code SET uses = uses + 1, last_used_at = ?"
                " WHERE code_hash = ?",
                (now, row["code_hash"]),
            )
        return record

    def revoke(self, short_id: str, now: Optional[float] = None) -> Optional[CodeRecord]:
        now = time.time() if now is None else now
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM access_code WHERE id = ?", (short_id.strip(),)
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "UPDATE access_code SET revoked_at = ? WHERE id = ?", (now, row["id"])
            )
        return _record(row)

    def all(self) -> list[CodeRecord]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM access_code ORDER BY created_at DESC"
            ).fetchall()
        return [_record(r) for r in rows]

    def has_active(self, now: Optional[float] = None) -> bool:
        return any(r.status(now) == "active" for r in self.all())


def _record(row: sqlite3.Row) -> CodeRecord:
    return CodeRecord(
        id=row["id"], label=row["label"], created_at=row["created_at"],
        expires_at=row["expires_at"], revoked_at=row["revoked_at"],
        uses=row["uses"], last_used_at=row["last_used_at"],
    )


# --------------------------------------------------------------------------
# Command line
#
#   docker compose exec api python -m app.access_codes add "Jane Doe" --days 14
#   docker compose exec api python -m app.access_codes list
#   docker compose exec api python -m app.access_codes revoke 3f9a21
# --------------------------------------------------------------------------

def _store() -> AccessCodes:
    from .config import get_settings
    return AccessCodes(get_settings().cache_db_path)


def main(argv: Optional[list[str]] = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        prog="python -m app.access_codes", description="Trial access codes."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    add = sub.add_parser("add", help="mint a code")
    add.add_argument("label", help="who it is for — shown only to you")
    add.add_argument("--days", type=int, default=None,
                     help="days until it expires; omit for no expiry")

    sub.add_parser("list", help="show every code ever issued")

    revoke = sub.add_parser("revoke", help="stop a code working")
    revoke.add_argument("id", help="the short id from `list`")

    args = parser.parse_args(argv)
    store = _store()

    if args.command == "add":
        code, record = store.issue(args.label, args.days)
        print(f"code     {code}")
        print(f"id       {record.id}   (use this to revoke; it is not the code)")
        print(f"label    {record.label}")
        print(f"expires  {_when(record.expires_at)}")
        print("\nThe code is shown once — only its hash is stored.")
        return 0

    if args.command == "list":
        records = store.all()
        if not records:
            print("No codes issued yet.")
            return 0
        print(f"{'id':8} {'status':8} {'uses':>5}  {'expires':16} {'last used':16} label")
        for r in records:
            print(f"{r.id:8} {r.status():8} {r.uses:>5}  "
                  f"{_when(r.expires_at):16} {_when(r.last_used_at):16} {r.label}")
        return 0

    record = store.revoke(args.id)
    if record is None:
        print(f"No code with id {args.id!r}. Run `list` to see them.")
        return 1
    print(f"Revoked {record.id} ({record.label}). It will no longer be accepted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
